export const PLAYER_NAMESPACE = '20f3bcf2-e4c3-4589-a7b5-9697afe1b1a8';
export const PLAYER_COLORS = [
  '#FF0000',
  '#00FF00',
  '#0000FF',
  '#FFFF00',
  '#FF00FF',
  '#00FFFF',
];
export const PLAYER_NAME_PARTS = [
    "Grimm",
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Eve",
    "Frank",
    "Grace",
    "Hannah",
    "Isaac",
    "Jack",
    "Jill",
    "Katie",
    "Liam",
    "Mia",
    "Noah",
    "Olivia",
    "Patrick",
    "Quinn",
    "Rachel",
    "Sam",
    "Taylor",
    "Victor",
    "Wendy",
    "Xander",
    "Yara",
    "Zack",
];
