min_entity_spawn_distance: 200
max_entity_spawn_distance: 300
max_raiders: 150
loadouts:
  - worker: 1
    collector_solar: 1
    habitat: 1
    scout: 1
    processor: 1
global_neutral_fields:
  - type: star_yellow
    count: 100
    origin:
      - 0
      - 0
    standard_deviation: 50000
  - type: theta
    count: 75
    origin:
      - 0
      - 0
    standard_deviation: 50000
  - type: minerals
    count: 225
    origin:
      - 0
      - 0
    standard_deviation: 50000
neutrals_near_spawn: []
starting_resources:
  food: 500
  minerals: 200
  energy: 250
