// Generated by scripts/generate-preload-entity-types.js — do not edit by hand.
// Source: entities.yaml (entity_types keys).

export const PRELOAD_ENTITY_TYPES = ["theta","planet_blue","star_yellow","minerals","collector_solar","worker","habitat","processor","factory","scout","raider","defense_pylon_v2","defense_pylon","collector_solar_v2"] as const;

export type PreloadEntityTypeId = (typeof PRELOAD_ENTITY_TYPES)[number];

/** Static content used by the content browser before a game server is running. */
export const ENTITY_CONTENT = [
  {
    "id": "theta",
    "builds": [],
    "definition": "fog_memory: retain_last_known\nspeed: 0\nz_index: -10\nsuppress_hover: true\nstop_radius: 0.75\nmass: 500\nhealth: 100\nvisibility_range: 4000\nvisual_scale: 2\nradiation_sources:\n  - radiation_type: theta\n    min_effective_distance_border_color: null\n    min_effective_distance_fill_color: \"#882cd6\"\n    full_damage_distance_border_color: null\n    full_damage_distance_fill_color: \"#a753ef\"\n    max_effective_distance_border_color: null\n    max_effective_distance_fill_color: \"#c384f8\"\n    min_effective_distance: 0\n    full_damage_distance: 700\n    max_effective_distance: 1200\n    damage_per_second: 6\nresource_node:\n  resource_type: energy\n  collection_mode: proximity\n  min_effective_distance: 350\n  max_effective_distance: 1600"
  },
  {
    "id": "planet_blue",
    "builds": [],
    "definition": "fog_memory: retain_last_known\nspeed: 0\nz_index: -2\nsuppress_hover: true\nstop_radius: 1\nmass: 500\nhealth: 100\nvisual_scale: 4\nresource_node:\n  resource_type: food\n  collection_mode: transport\n  min_effective_distance: 20\n  max_effective_distance: 50"
  },
  {
    "id": "star_yellow",
    "builds": [],
    "definition": "fog_memory: retain_last_known\nspeed: 0\nvisibility_range: 40000\nz_index: -10\nsuppress_hover: true\nstop_radius: 1\nmass: 500\nhealth: 100\nvisual_scale: 15\nradiation_sources:\n  - radiation_type: stellar_heat\n    min_effective_distance_border_color: null\n    min_effective_distance_fill_color: \"#ef4444\"\n    full_damage_distance_border_color: null\n    full_damage_distance_fill_color: \"#f97316\"\n    max_effective_distance_border_color: null\n    max_effective_distance_fill_color: \"#facc15\"\n    min_effective_distance: 0\n    full_damage_distance: 900\n    max_effective_distance: 1200\n    damage_per_second: 2\nresource_node:\n  resource_type: energy\n  collection_mode: proximity\n  min_effective_distance: 10\n  max_effective_distance: 1500"
  },
  {
    "id": "minerals",
    "builds": [],
    "definition": "fog_memory: retain_last_known\nspeed: 0\nz_index: -1\nstop_radius: 1\nmass: 500\nhealth: 100\nvisibility_range: 1000\nresource_node:\n  resource_type: minerals\n  collection_mode: transport\n  min_effective_distance: 20\n  max_effective_distance: 50"
  },
  {
    "id": "collector_solar",
    "builds": [
      "collector_solar_v2"
    ],
    "definition": "fog_memory: forget_when_hidden\nspeed: 20\nstop_radius: 1\nmass: 500\nhealth: 100\nhull_radius: 12\ncombat_targetable: true\nsensor:\n  range: 400\n  cost_per_minute:\n    energy: 0.1\nbuild_cost:\n  minerals: 100\n  energy: 50\nradiation_shielding:\n  stellar_heat:\n    distance_offset: 90\n    damage_multiplier: 0.1\ncollector:\n  vfx: solar_proximity\n  collects:\n    - energy\n  proximity_rate_per_second: 12\n  transport_rate_per_second: 0\n  carry_capacity: 0\nbuilds:\n  - entity_type_id: collector_solar_v2"
  },
  {
    "id": "worker",
    "builds": [
      "collector_solar",
      "habitat",
      "defense_pylon",
      "factory"
    ],
    "definition": "fog_memory: forget_when_hidden\nspeed: 90\nstop_radius: 0.75\nmass: 1\nhealth: 200\nhull_radius: 50\ncombat_targetable: true\nsensor:\n  range: 400\n  cost_per_minute:\n    energy: 0.1\ncombat:\n  acquisition_range: 250\n  on_near_enemy_strategy: approach\n  attacks:\n    - id: dismantle\n      type: dismantle\n      damage: 4\n      cooldown_ticks: 60\n      priority: 100\n      contact_tolerance: 2\nbuild_cost:\n  minerals: 50\n  energy: 50\nmaintenance_cost_per_minute:\n  energy: 1\n  food: 2\ncollector:\n  vfx: mineral_transport\n  collects:\n    - minerals\n    - food\n  transport_rate_per_second: 10\n  carry_capacity: 120\n  deposit_entity_types:\n    - processor\n    - habitat\nrepair:\n  range: 150\n  cost_per_min:\n    energy: 60\n    minerals: 60\n  efficiency: 1\nbuilds:\n  - entity_type_id: collector_solar\n    spend_rates:\n      minerals: 1.2\n      energy: 1.2\n  - entity_type_id: habitat\n    spend_rates:\n      minerals: 1.2\n      energy: 1.2\n  - entity_type_id: defense_pylon\n    spend_rates:\n      minerals: 1.2\n      energy: 1.2\n  - entity_type_id: factory\n    spend_rates:\n      minerals: 1.2\n      energy: 1.2"
  },
  {
    "id": "habitat",
    "builds": [
      "worker"
    ],
    "definition": "fog_memory: forget_when_hidden\nspeed: 60\nstop_radius: 0.5\nmass: 4\nhealth: 400\nhull_radius: 50\nvisual_scale: 2\ncombat_targetable: true\nrefinery:\n  accepts:\n    - food\n    - minerals\nbuild_cost:\n  minerals: 1000\n  energy: 1000\nmaintenance_cost_per_minute:\n  food: 60\nsensor:\n  range: 4000\n  cost_per_minute:\n    energy: 5\nbuilds:\n  - entity_type_id: worker\n    spend_rates:\n      minerals: 0.8\n      energy: 0.8\ncollector:\n  collects:\n    - energy\n  proximity_rate_per_second: 5\n  transport_rate_per_second: 0\n  carry_capacity: 0"
  },
  {
    "id": "processor",
    "builds": [],
    "definition": "fog_memory: forget_when_hidden\nspeed: 60\nstop_radius: 0.5\nmass: 7\nhealth: 150\nhull_radius: 16\nvisual_scale: 1.5\nbuild_cost:\n  minerals: 100\n  energy: 100\nsensor:\n  range: 400\n  cost_per_minute:\n    energy: 0.1\ncombat_targetable: true\nmaintenance_cost_per_minute:\n  energy: 5\n  food: 5\nrefinery:\n  accepts:\n    - minerals"
  },
  {
    "id": "factory",
    "builds": [
      "scout",
      "processor",
      "habitat"
    ],
    "definition": "fog_memory: forget_when_hidden\nspeed: 60\nstop_radius: 0.5\nmass: 7\nhealth: 150\nhull_radius: 16\ncombat_targetable: true\nvisual_scale: 2\nbuild_cost:\n  minerals: 600\n  energy: 600\nsensor:\n  range: 400\n  cost_per_minute:\n    energy: 0.1\nbuilds:\n  - entity_type_id: scout\n    spend_rates:\n      minerals: 1\n      energy: 1\n  - entity_type_id: processor\n    spend_rates:\n      minerals: 1\n      energy: 1\n  - entity_type_id: habitat\n    spend_rates:\n      minerals: 2.2\n      energy: 2.2"
  },
  {
    "id": "scout",
    "builds": [],
    "definition": "fog_memory: forget_when_hidden\nspeed: 500\nstop_radius: 0.5\nmass: 0.6\nhealth: 60\nhull_radius: 10\ncombat_targetable: true\nbuild_cost:\n  minerals: 75\n  energy: 50\ncombat:\n  acquisition_range: 450\n  on_near_enemy_strategy: approach\n  attacks:\n    - id: laser\n      type: laser\n      range: 120\n      damage: 2\n      cooldown_ticks: 75\n      priority: 0\nsensor:\n  range: 5000\n  cost_per_minute:\n    energy: 2.5"
  },
  {
    "id": "raider",
    "builds": [],
    "definition": "fog_memory: forget_when_hidden\nspeed: 110\nstop_radius: 0.5\nmass: 0.8\nhealth: 40\nhull_radius: 50\ncombat_targetable: true\nvisual_scale: 0.75\ncombat:\n  acquisition_range: 1200\n  on_near_enemy_strategy: approach\n  attacks:\n    - id: laser\n      type: laser\n      range: 180\n      damage: 8\n      cooldown_ticks: 100\n      priority: 0\nsensor:\n  range: 500\n  cost_per_minute:\n    energy: 2.5"
  },
  {
    "id": "defense_pylon_v2",
    "builds": [],
    "definition": "fog_memory: forget_when_hidden\nbuild_cost:\n  minerals: 100\n  energy: 50\nmaintenance_cost_per_minute:\n  energy: 200\nspeed: 5\nstop_radius: 0.5\nmass: 1\nhealth: 500\nhull_radius: 15\ncombat:\n  acquisition_range: 500\n  on_near_enemy_strategy: stay\n  attacks:\n    - id: laser\n      type: laser\n      range: 500\n      damage: 3\n      cooldown_ticks: 67\n      priority: 0\nsensor:\n  range: 500\n  cost_per_minute:\n    energy: 2.5"
  },
  {
    "id": "defense_pylon",
    "builds": [
      "defense_pylon_v2"
    ],
    "definition": "fog_memory: forget_when_hidden\nbuild_cost:\n  minerals: 100\n  energy: 50\nmaintenance_cost_per_minute:\n  energy: 200\nspeed: 5\nstop_radius: 0.5\nmass: 1\nhealth: 500\nhull_radius: 15\ncombat:\n  acquisition_range: 500\n  on_near_enemy_strategy: stay\n  attacks:\n    - id: laser\n      type: laser\n      range: 500\n      damage: 2\n      cooldown_ticks: 51\n      priority: 0\nsensor:\n  range: 500\n  cost_per_minute:\n    energy: 2.5\nbuilds:\n  - entity_type_id: defense_pylon_v2"
  },
  {
    "id": "collector_solar_v2",
    "builds": [],
    "definition": "fog_memory: forget_when_hidden\nspeed: 20\nstop_radius: 1\nmass: 500\nhealth: 100\nhull_radius: 12\ncombat_targetable: true\nvisual_scale: 1.25\nsensor:\n  range: 400\n  cost_per_minute:\n    energy: 0.1\nbuild_cost:\n  minerals: 100\n  energy: 50\nradiation_shielding:\n  stellar_heat:\n    distance_offset: 90\n    damage_multiplier: 0.1\ncollector:\n  vfx: solar_proximity\n  collects:\n    - energy\n  proximity_rate_per_second: 15\n  transport_rate_per_second: 0\n  carry_capacity: 0"
  }
] as const;
