// Generated by scripts/generate-preload-entity-types.js — do not edit by hand.
// Source: entities.yaml (entity_types keys).

export const PRELOAD_ENTITY_TYPES = ["theta","worker","habitat","processor","factory","scout"] as const;

export type PreloadEntityTypeId = (typeof PRELOAD_ENTITY_TYPES)[number];
