pub mod config;
pub mod delta;
pub mod engine;
pub mod io;
pub mod physics;

pub mod pb {
    // generated by prost-build (one file per package)
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/pb/bitwars.rs"));
}

// (Optional) quick unit test that breaks if the schema shape changes
#[cfg(test)]
mod tests {
    use super::pb;
    #[test]
    fn proto_sanity() {
        let v = pb::Vec2 { x: 1.0, y: 2.0 };
        let _e = pb::Entity {
            id: 1,
            pos: Some(v),
            vel: None,
            force: None,
        };
    }
}
